#!/bin/bash
# JobCopilot Complete Testing Script
# Run this in keshav conda environment

echo "🧪 JobCopilot Complete Testing Guide"
echo "===================================="
echo ""

echo "📋 Prerequisites Check:"
echo "✓ Backend running on http://localhost:8000"
echo "✓ Frontend running on http://localhost:5174"
echo "✓ Database reset completed"
echo ""

echo "🔐 Test Account Credentials:"
echo "Name: Roopesh"
echo "Email: admin@gmail.com"
echo "Password: admin@123"
echo ""

echo "📝 Manual Testing Checklist:"
echo ""
echo "1️⃣ SIGNUP & LOGIN TEST"
echo "   □ Go to http://localhost:5174"
echo "   □ Click 'Get Started' or 'Sign Up'"
echo "   □ Fill in:"
echo "     - Name: Roopesh"
echo "     - Email: admin@gmail.com"
echo "     - Password: admin@123"
echo "     - Confirm Password: admin@123"
echo "   □ Check 'I agree to terms' checkbox"
echo "   □ Click 'Sign Up'"
echo "   □ Verify redirect to dashboard"
echo ""

echo "2️⃣ JOBS PAGE TEST"
echo "   □ Navigate to /jobs"
echo "   □ Verify premium glassmorphism UI visible"
echo "   □ Check stats cards show correct counts"
echo "   □ Verify job cards display:"
echo "     - Job titles (fully visible)"
echo "     - Company names"
echo "     - Job descriptions"
echo "     - Location"
echo "     - Salary ranges"
echo "     - Skills required"
echo "   □ Test search functionality"
echo "   □ Click 'Filters' button"
echo "   □ Test filter options:"
echo "     - Job Type"
echo "     - Work Mode"
echo "     - Salary Range"
echo "     - Experience Level"
echo "   □ Click 'View Details' on a job"
echo "   □ Verify modal opens with full details"
echo "   □ Click 'Apply' button"
echo "   □ Verify external redirect (new tab opens)"
echo ""

echo "3️⃣ UPLOAD RESUME TEST"
echo "   □ Navigate to /upload-resume"
echo "   □ Drag & drop a PDF/DOCX resume OR click 'Choose File'"
echo "   □ Verify upload progress animation"
echo "   □ Check extracted skills display"
echo "   □ Check extracted experience display"
echo "   □ Verify 'Resume analyzed successfully!' toast"
echo ""

echo "4️⃣ RESUME-BASED SMART FILTER TEST"
echo "   □ After uploading resume, go back to /jobs"
echo "   □ Click 'Filters' button"
echo "   □ Enable 'Smart Match (Based on Your Resume)' checkbox"
echo "   □ Verify jobs filter to show only matching skills"
echo "   □ Check each job card shows:"
echo "     - Skill match percentage badge"
echo "     - Color coding (green >70%, yellow >40%, blue <40%)"
echo "   □ Click 'View Details' on a matched job"
echo "   □ Verify 'Skill Match Analysis' section shows:"
echo "     - Matched Skills (green badges)"
echo "     - Skills to Learn (orange badges)"
echo ""

echo "5️⃣ CHATBOT TEST"
echo "   □ Navigate to /chatbot"
echo "   □ Verify animated robot avatar in header"
echo "   □ Check robot is in 'idle' mood (gentle bobbing)"
echo "   □ Type a message: 'How do I optimize my resume?'"
echo "   □ Click Send"
echo "   □ Verify robot changes to 'thinking' mood"
echo "   □ Check response appears with:"
echo "     - Small robot avatar in message bubble"
echo "     - Proper formatting"
echo "     - Relevant content"
echo "   □ Test suggestions (click one)"
echo "   □ Verify conversation history maintained"
echo ""

echo "6️⃣ NOTIFICATION SYSTEM TEST"
echo "   □ Look at top-right navbar"
echo "   □ Verify bell icon visible"
echo "   □ Click bell icon"
echo "   □ Check dropdown opens"
echo "   □ Verify 'No notifications yet' message (fresh DB)"
echo "   □ Check dropdown styling and animations"
echo ""

echo "7️⃣ ANALYTICS PAGE TEST"
echo "   □ Navigate to /analytics"
echo "   □ Verify page loads (may show 'No data' for fresh account)"
echo "   □ Check charts render properly"
echo "   □ Verify loading animation if data is loading"
echo ""

echo "8️⃣ MY APPLICATIONS TEST"
echo "   □ Navigate to /applications or /my-applications"
echo "   □ After applying to jobs, verify applications show"
echo "   □ Check application cards display:"
echo "     - Job title"
echo "     - Company"
echo "     - Application date"
echo "     - Status"
echo "   □ Click 'View Details' (if available)"
echo ""

echo "9️⃣ PROFILE PAGE TEST"
echo "   □ Navigate to /profile"
echo "   □ Verify current user info displays:"
echo "     - Name: Roopesh"
echo "     - Email: admin@gmail.com"
echo "   □ Try updating profile information"
echo "   □ Click 'Save' or 'Update'"
echo "   □ Verify changes persist after page refresh"
echo ""

echo "🔟 NAVIGATION & UI TEST"
echo "   □ Test sidebar/navbar navigation"
echo "   □ Click each menu item"
echo "   □ Verify smooth transitions"
echo "   □ Check dark mode (if toggle exists)"
echo "   □ Test responsive design (resize browser)"
echo "   □ Verify all icons load properly"
echo "   □ Check for console errors (F12 → Console)"
echo ""

echo "1️⃣1️⃣ ADMIN FEATURES TEST (if admin account)"
echo "   □ Navigate to /admin/dashboard"
echo "   □ Verify admin panel accessible"
echo "   □ Test job creation:"
echo "     - Click 'Post Job' or 'Create Job'"
echo "     - Fill in job details"
echo "     - Click 'Create'"
echo "     - Verify job appears in /jobs"
echo "   □ Test job editing"
echo "   □ Test job deletion"
echo ""

echo "1️⃣2️⃣ LOGOUT TEST"
echo "   □ Click user avatar/menu in top-right"
echo "   □ Click 'Sign Out' or 'Logout'"
echo "   □ Verify redirect to landing page"
echo "   □ Try accessing protected routes"
echo "   □ Verify redirect to login"
echo ""

echo ""
echo "🐛 COMMON ISSUES TO CHECK:"
echo "   □ No CORS errors in console"
echo "   □ All API calls succeed (check Network tab)"
echo "   □ No 404 errors for assets"
echo "   □ Images/icons load properly"
echo "   □ Animations smooth (no jank)"
echo "   □ Toast notifications appear and disappear"
echo "   □ Loading states show appropriately"
echo "   □ Error messages are user-friendly"
echo ""

echo "✅ EXPECTED RESULTS:"
echo "   ✓ All pages load without errors"
echo "   ✓ Job cards show all details clearly"
echo "   ✓ Resume upload extracts skills correctly"
echo "   ✓ Smart filters work with uploaded resume"
echo "   ✓ Skill match percentages display"
echo "   ✓ Apply button opens external URLs"
echo "   ✓ Chatbot responds with Gemini AI"
echo "   ✓ Robot avatar animates smoothly"
echo "   ✓ Notifications system functional"
echo "   ✓ Profile updates persist"
echo ""

echo "📊 TESTING COMPLETE!"
echo "Report any issues found during testing."
